INTYGFV-16084: Added GlobalExceptionHandlerController that handles communication errors for integrated services.
sklintyg/minaintyg pull request #294
Opened 2023-11-10 14:13 UTC by ChrilleSigerhed

2023-11-10 14:26 UTC, ChrilleSigerhed commented
Regarding this function:
```java
       .onErrorMap(
            WebClientRequestException.class,
            ExceptionThrowableFunction.get(APPLICATION_WEBCERT)
        )
```
This will map any exception of type WebClientRequestException to our custom Exception called IntegrationServiceException. This exception only occurs if we are not able to establish communication with the service we are looking for.

If we want to throw this exception even if a 500-error occurs in the service we are calling, some modification will be needed.

2023-11-13 10:03 UTC, mww-sopra-steria requested changes
Looks good! But I have a few thoughts that we should consider:
1) If the call to the integrated service receives timeout we should also return a 503.
2) We need to log the stack trace when logging the error.
3) Need to include the original exception in the IntegrationServiceException.
4) Also add this to the intyg-proxy-service integration

2023-11-14 10:42 UTC, mww-sopra-steria approved these changes
Well done! Just change the constant for intyg-proxy-service

2023-11-14 10:42 UTC, mww-sopra-steria commented on integration-intyg-proxy-service/src/main/java/se/inera/intyg/minaintyg/integration/intygproxyservice/person/client/GetPersonFromIntygProxyServiceImpl.java
> +import static se.inera.intyg.minaintyg.integration.common.constants.ApplicationConstants.APPLICATION_WEBCERT;
Should use an application constant for INTYG_PROXY_SERVICE

2023-11-14 11:06 UTC, merged